kind: pipeline
name: default

steps:
  - name: build
    image: golang:1.13
    commands:
      - make build

  - name: publish
    image: plugins/docker:18
    settings:
      dockerfile: ./Dockerfile
      repo: taniwhy/mochi-match-rest
      tags: latest
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      password:
        from_secret: SSH_PASSWORD
      port: 22
      script:
        - cd /var/www/mochi-match-rest
        - sh deploy.sh

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOCK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOCK_TOKEN
      username: >
        close me
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}

trigger:
  event:
    - push
services:
  - name: db
    image: postgres:10.5
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mochi_match
  - name: redis
    image: redis:4.0.6
    ports:
      - 6379
