kind: pipeline
name: default

steps:
  - name: build
    image: golang
    commands:
      - make build

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 719600438395142232
      webhook_token: dIVe_GjWk7chVq9ZGoDzobc6ZeXeQpSJSaZPZ7VuquUxsUUN9YVTYwxX017H4LRzo6gk
      tts: true
      message: "Testing from drone image"
trigger:
  event:
    - push
