kind: pipeline
name: default

steps:
  - name: discord notification
    image: appleboy/drone-discord
    settings:
      tts: true
      webhook_id:
        from_secret: DISCORD_WEBHOCK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOCK_TOKEN
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
trigger:
  event:
    - push
services:
  - name: db
    image: postgres:10.5
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mochi_match
  - name: redis
    image: redis:4.0.6
    ports:
      - 6379
