---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: vet
    pull: always
    image: golang:1.13
    commands:
      - go vet ./...
    environment:
      GO111MODULE: on

  - name: test
    image: golang:1.13
    commands:
      - make test
    environment:
      GO111MODULE: on

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: DISCORD_WEBHOCK_ID
      webhook_token:
        from_secret: DISCORD_WEBHOCK_TOKEN
      username: >
        close me
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
