development:
  dialect: postgres
  datasource: 'dbname=mochi_match host=localhost user=postgres password=postgres port=5432 sslmode=disable'
  dir: db/dev-migrations
  table: migrations

production:
  dialect: postgres
  datasource: ${DB_URL}
  dir: db/migrations
  table: migrations
