version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "mochi-match-app"
    volumes:
      - mochimatch_postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "8000:8000"
    volumes:
      - .:/go/src/taniwhy/mochi-match-rest
    command: make run
    depends_on:
      - db
      - redis
  db:
    image: postgres:10.5
    container_name: "mochi-match-postgres"
    volumes:
      - mochimatch_postgres_dev_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  redis:
    image: "redis:4.0.6"
    container_name: "mochi-match-redis"
    ports:
      - "6379:6379"
volumes:
  mochimatch_postgres_dev_data:
    driver: local

networks:
  default:
    external:
      name: shared
