version: "3"

services:
  db:
    container_name: "task_db"
    image: postgres:10.5
    volumes:
      - mochi_match_dev_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

volumes:
  mochi_match_dev_data:
    driver: local
